SELECT * FROM customer
LIMIT 5;

--Q1. What is the total revenue generated by male vs. female customers?

SELECT gender, SUM(purchase_amount) AS rev
FROM customer
GROUP BY gender
ORDER BY SUM(purchase_amount) DESC

--Q2. Which customers used a discount but still spent more than the average purchase amount? 

SELECT customer_id, purchase_amount
FROM customer
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) AS avg_purchase FROM customer)

-- Q3. Which are the top 5 products with the highest average review rating?

SELECT item_purchased, ROUND(AVG(review_rating::NUMERIC), 2) AS avg_rating
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 

SELECT shipping_type, ROUND(AVG(purchase_amount::NUMERIC), 2) AS "Average Purchase Amount per Shipping Type"
FROM customer
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type
ORDER BY AVG(purchase_amount) DESC

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.

SELECT subscription_status, 
	COUNT (customer_id),
	ROUND(AVG(purchase_amount::NUMERIC), 2) AS "Average Spend", 
	ROUND(SUM(purchase_amount::NUMERIC), 2) AS "Total Revenue"
FROM customer
GROUP BY subscription_status


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased, 
	ROUND(100.0*SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*), 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5

--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 

with customer_type AS (SELECT customer_id,
CASE WHEN previous_purchases = 1 THEN 'New'
	WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
	ELSE 'Loyal'
	END AS customer_segment
FROM customer)

SELECT customer_segment, COUNT (*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment

--Q8. What are the top 3 most purchased products within each category? 

WITH item_rank AS (
SELECT category, item_purchased,
	COUNT(customer_id) AS total_sales,
	ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS sales_rank
FROM customer
GROUP BY category, item_purchased
)

SELECT sales_rank, category, item_purchased, total_sales
FROM item_rank
WHERE sales_rank <=3;

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

SELECT subscription_status, 
	COUNT (customer_id) as total_buyers, 
	SUM (previous_purchases) AS "Total Repeat Purchases"
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 

SELECT 
	age_group, 
	SUM(purchase_amount)
FROM customer
GROUP BY age_group
ORDER BY SUM(purchase_amount) DESC;


